PAGE 60,132
TITLE PRACT10.EXE
.MODEL SMALL
;_____________________________________
.STACK 64
.DATA               ;COMIENZAN LOS DATOS
REG0 DW 00001H      ;ETIQUETA REG0
REG1 DW 00001H      ;ETIQUETA REG1
REG2 DW 00001H      ;ETIQUETA REG2
COLOR DB 00H        ;ETIQUETA CON LA VARIABLE COLOR
MSJE DB "Ricardo David Lopez Arellano :)","$"  ;MSJ A MOSTRAR
;_____________________________________

.CODE               ;COMIENZA EL CODIGO
INICIO PROC FAR     ;FUNCION LLAMADA INICIO
    MOV AX, @DATA   ;GUARDAMOS EL VALOR DE @DATA EN AX
    MOV DS, AX      ;MOVEMOS AX A DS
    CALL PANT1      ;LLAMADA PARA LA VENTANA PRINCIPAL
    CALL CAMBIO     ;LLAMADA PARA HACER EL RETARDO
    CALL CURSOR1    ;LLAMADA PARA EL CURSOR
    MOV AX,4C00H    ;PARA FINALIZAR EL PROGRAMA
    INT 21H         ;INTERRUPCION 21H
INICIO ENDP         ;FIN FUNC
;_____________________________________

PANT0 PROC NEAR     ;FUNC PARA LA PANTALLA DEL RECUADRO
    MOV AX,0700H    ;DEFINE LA PANTALLA
    MOV BH,COLOR    ;COLOR QUE VA CAMBIANDO DENTRO DE LA VENTANA
    MOV CX,0209H    ;ANCHO DE LA VENTANA
    MOV DX,1549H    ;ALTO DE LA VENTANA
    INT 10H         ;INTERRUPCION 10H
    RET             ;RETORNA
PANT0 ENDP          ;FIN FUNC
;_____________________________________

PANT1 PROC NEAR     ;FUNC PARA LA VENTANA DEL FONDO
    MOV AX,0600H    ;DEFINE LA VENTANA
    MOV BH,90H ;10H ;COLOR DEL FONDO DE LA VENTANA
    MOV CX,0000H    ;ANCHO DE LA VENTANA
    MOV DX,1950H    ;ALTO DE LA VENTANA
    INT 10H         ;INTERRUPCION 10H
    RET             ;RETORNA
PANT1 ENDP          ;FIN FUNC
;____________________________________

CURSOR0 PROC NEAR   ;FUNCION DEL CURSOR
    MOV AH,02H      ;DEFINE EL CURSOR
    MOV BH,00H      ;MOVEMOS 00 A BH
    MOV DX,0C1AH    ;MOVEMOS A DX
    INT 10H         ;INTERRUPCION 10H
    RET             ;RETORNA AL PROCESO PRINCIPAL
CURSOR0 ENDP        ;FIN FUNC
;_____________________________________

CURSOR1 PROC NEAR   ;FUNC CURSOR 2
    MOV AH,02H      ;MOVER 02H A AH
    MOV BH,00H      ;MOVER 00H A BH
    MOV DX,1400H    ;MOVER 1400H A DX
    INT 10H         ;INTERRUPCION 10H
    RET             ;RETORNA
CURSOR1 ENDP        ;FIN FUNC
;_____________________________________

CAMBIO PROC NEAR    ;FUNC DE HACER EL CAMBIO
    CALL PANT0      ;LLAMADA A DEFINIR LA PANTALLA
    CALL CURSOR0    ;LLAMADA A DEFINIR EL CURSOR
    CALL DESP       ;LLAMADA A DEFINIR EL DESPLIEGUE DE MSJ
    CALL RETARd
    CALL RETARi
    CALL RETARd
    CALL RETARi
    INC COLOR       ;INCREMENTA EL VALOR A 1 DE CADA COLOR
    CMP COLOR,0FFH  ;COMPARAMOS EL COLOR CON OFFH
    JE SALE         ;SI EL COLOR ES IGUAL SALTA A LA ETIQUETA SALIR
    JMP CAMBIO      ;SALTA AL COMIENZO
    SALE: RET       ;SALE Y RETORNA AL PRINCIPIO
CAMBIO ENDP         ;FIN FUNC
;_____________________________________

DESP PROC NEAR      ;FUNC DE DESPLEGAR
    MOV AH,09H      ;DESPLIEGA EL MSJ
    LEA DX, MSJE    ;MOVEMOS LA DIRECCION DE MEMORIA A DX
    INT 21H         ;INTERRUPCIO 21H
    RET             ;RETORNA
DESP ENDP           ;FIN FUNC
;_____________________________________

RETARd PROC NEAR        ;FUNC RETARDO1
    DECR0:              ;DECREMENTO 0
        DEC REG0        ;DECREMENTA EL VALOR DE REG0
        CMP REG0,00000H ;COMPARA EL VALOR DE REG0 CON 0000H
        JE DECR1        ;SI SON IGUALES SALTA A DECR1
        JMP DECR0       ;SALTA A LA ETIQUETA DECR0
    DECR1:              ;DECREMENTO 1
        DEC REG1        ;DECREMENTA EL VALOR DE REG1
        CMP REG1,00000H ;COMPARA REG1 CON 00000H
        JE DECR2        ;SI SON IGUALES SALTA A ETIQUETA DECR2
        JMP DECR1       ;SALTA A LA ETIQUETA DECR1
    DECR2:              ;DECREMENTO 2
        DEC REG2        ;DECREMENTA EL VALOR DECR2
        CMP REG2,00000H ;COMPARA EL VALOR RG2 CON 0000H
        JE SALIR0       ;SI SON IGUALES SALTA A LA ETIQUETA SALIR
        JMP DECR2       ;SALTA A LA ETIQUETA DECR2
    SALIR0: RET         ;ETIQUETA SALIR Y RETORNA A PROCESO CAMBIO
RETARd ENDP             ;FIN FUNC
;_____________________________________

RETARi PROC NEAR        ;FUNC RETARDO2
    INCR0:              ;INCREMENTO 0
        INC REG0        ;INCREMENTA EL VALOR DE REG0
        CMP REG0,00005H ;COMPARAMOS REG0 CON 0FFFFH
        JE INCR1        ;SI ES IGUAL SALTA A LA ETIQUETA INCR1
        JMP INCR0       ;SALTA A INCR0
    INCR1:              ;INCREMENTO 1
        INC REG1        ;INCREMENTA EL VALOR DE REG1
        CMP REG1,00005H ;COMPARAMOS REG1 CON 0FFFFH
        JE INCR2        ;SI ES IGUAL SALTA A LA ETIQUETA INCR2
        JMP INCR1       ;SALTA A INCR1
    INCR2:              ;INCREMENTO 2
        INC REG2        ;INCREMENTA EL VALOR DE REG2
        CMP REG2,00005H ;COMPARAMOS REG2 CON 0FFFFH
        JE SALIR1       ;SI ES IGUAL SALTA A LA ETIQUETA SALIR1
        JMP INCR2       ;SALTA A INCR2
        SALIR1: RET     ;ETIQUETA SALIR Y RETORNA A PROCESO CAMBIO
RETARi ENDP             ;FIN FUNC
;_____________________________________

END INICIO          ;FIN PROGRAMA