TITLE P15 ASCII A BINARIO
.MODEL SMALL            ;MODELO
.CODE                   ;SEGMENTO DE CODIGO
ORG 100H                ;PAGINAS           
BEGIN: JMP SHORT MAIN   ;FUNC PRINCIPAL

ASCVAL DB '123'         ;DATOS EN ASCII
BINVAL DW 0             ;CADENA PARA CONVERTIR A BINARIO
ASCLEN DW 4             ;CADENA ASCLEN
MULT10 DW 1             ;CADENA MULT10

MAIN PROC NEAR          ;AQUI COMIENZA LA FUNC
MOV BX, 1O              ;FACTOR DE MULTIPLICACION
MOV CX, 04              ;CONTADOR DEL CICLO
LEA SI,ASCVAL+3         ;DIRECCION DE ASCVAL
    
B20:
MOV AL,[SI]             ;SELECCIONA EL CARACTER ASCII
AND AX, 000FH           ;BORRA LA ZONA 3
MUL MULT10              ;MULTIPLICA POR UN FACTOR 10
ADD BINVAL,AX           ;SUMA AL BINARIO
MOV AX,MULT10           ;CALCULA EL SIGUIENTE
MUL BX                  ;FACTOR DE 10
MOV MULT10,AX           ;MOVEMOS MULT10 A AX
DEC SI                  ;EL ULTIMO CARACTER DE ASCII
LOOP B20                ;SI NO, ENTONCES CONTINUA
MOV AX,4C00H            ;MOVEMOS 4C00H A AX
INT 21H                 ;INTERRUPCION 21H
    
MAIN ENDP               ;SALIR DE LA FUNC
END BEGIN               ;SALIR DEL PROGRAMA
    
    