PAGE 60,132          ;# DE FILAS Y COLUMNAS
TITLE PROG2.EXE      ;NOMBRE DEL PROGRAMA
.MODEL SMALL         
.STACK 64            ;LONGITUD DE LA PILA

;_______________________________

.DATA                ;DESDE AQUI VAN LOS DATOS
DAT1 DB 05H          ;DAT1 Í 05
DAT2 DB 10H          ;DAT2 Í 10
DAT3 DB ?            ;DAT3 Í VALOR INDEFINIDO
DAT4 DB 01001000B    ;DAT4 Í (VALOR BINARIO)
DAT5 DB 10 DUP (0)   ;DEFINE 10 CEROS
DAT7 DB 'HOLA'       ;DEFINE CADENA
DAT8 DB 08,'MAYO',01 ;DEFINE FECHA
DAT9 DW 0FFFFH       ;CONSTANTE HEX
DAT10 DD ?           ;DAT10 Í VALOR INDEFINIDO
 
DATB DD 325772       ;VALOR DECIMAL
DATC DW ?            ;DATC Í VALOR INDEFINIDO

DATD DB 10 DUP (?)   ;10 ESPACIOS EN BLANCO
TIME EQU 10          ;VALOR PERMANENTE A UN MODULO
DATE DB TIME DUP (?) ;10 ESPACIOS EN BLANCO
;_______________________________

.CODE                ;DESDE AQUI VA EL CODIGO
BEGIN PROC FAR       ;INICIO
MOV AH, DAT1         ;MUEVE DAT1 A AX
ADD AH, DAT2         ;SUMA LO QUE HAY EN AX(05) CON DAT2(10)
MOV DAT3, AH         ;RESULTADO DE LA SUMA
MOV AH,TIME          ;MUEVE EL TIME A AH
MOV AX,4C00H         ;SALIDA A D0S
INT 21H              ;INVOCA LOS SERVICIOS A LA FUNCION DOS

BEGIN ENDP           ;FIN DEL CODIGO
                     ;FIN DEL PROGRAMA
END BEGIN