PAGE 60,132
TITLE PROG3.EXE  ;TITULO DEL PROGRAMA
.MODEL SMALL     ;DEFINE EL MODELO

;___________________________________

.CODE            ;COMIENZA EL CODIGO
ORG 100H         

MAIN PROC NEAR   ;DEFINE EL PROCESO
MOV AX,01        ;MUEVE EL VALOR '01' A AX
MOV BX,01        ;MUEVE EL VALOR '01' A BX
MOV CX,01        ;MUEVE EL VALOR '01' A CX
A20: ADD AX,01   ;AGREGA ETIQUETA A LA FUNCION
ADD BX, AX       ;SUMA EL VALOR DE AX Y BX
SHL CX,1         ;HACE UN DESPLAZAMIENTO DE BITS A LA IZQUIERDA
JMP A20          ;SALTA A LA DIRECCION MENCIONADA
MOV AX,4C00H     ;ASIGNA EL VALOR 4C00H
INT 21H          ;LLAMA A LA INTERRUPCION 21H

MAIN ENDP        ;DEFINE EL FIN DEL PROCESO
END MAIN