PAGE 60,132
TITLE PROG4.EXE
.MODEL SMALL
;___________________________________

.CODE           ;COMIENZA EL CODIGO
ORG 100H
MAIN PROC NEAR  ;DEFINE EL PROCESO
MOV AX,01       ;MUEVE EL VALOR 1 EN DECIMAL A AX
MOV BX,01       ;MUEVE EL VALOR 1 EN DECIMAL A BX
MOV DX,01       ;MUEVE EL VALOR 1 EN DECIMAL A DX
MOV CX,10       ;MUEVE EL VALOR 10 EN DECIMAL A CX
A20: INC AX     ;INCREMENTA 1 A AX
ADD BX, AX      ;SUMA BX + AX 
SHL DX,1        ;SE HACE EL DESPLAZAMIENTO DE BITS
LOOP A20        ;SE DESPLAZA A LA ETIQUETA A20
MOV AX,4C00H    ;ASIGNA EL VALOR 4C00 HEXADECIMMAL
INT 21H         ;LLAMA A LA INTERRUPCION 21H
MAIN ENDP       ;FIN DEL PROCESO
END MAIN