PAGE 60,132
TITLE PROG9.EXE
.MODEL MEDIUM
.STACK 64
;_____________________________________

.DATA                     ;COMIENZO DE DATOS

ENTRADA1 LABEL BYTE       ;ESPACIO DE MEMORIA TIPO BYTE
LONMAX1 DB 20             ;LONGITUD MAX DE ENTRADA
LONREAL1 DB ?             ;VARIABLE QUE ALMACENARA LA LONG DE LA CADENA
INTRO1 DB 21 DUP (' ')    ;21 ESPACIOS EN LA MEMORIA

ENTRADA2 LABEL BYTE       ;ESPACIO DE MEMORIA TIPO BYTE
LONMAX2 DB 25             ;LONG MAX DE ENTRADA
LONREAL2 DB ?             ;ALMACENA LA LONG REAL DE LA CADENA
INTRO2 DB 21 DUP (' ')    ;21 ESPACIOS EN LA MEMORIA

ENTRADA3 LABEL BYTE       ;ESPACIO DE MEMORIA TIPO BYTE
LONMAX3 DB 20             ;LONG MAX DE ENTRADA
LONREAL3 DB ?             ;ALMACENA LA LONG REAL DE LA CADENA
INTRO3 DB 21 DUP (' ')    ;21 ESPACIOS EN LA MEMORIA

ETIQ1 DB 'NOMBRE : ','$'  ;DECALARA VARIABLE CON CADENA
ETIQ2 DB 'CARRERA : ','$' ;DECALARA VARIABLE CON CADENA
ETIQ3 DB 'REGISTRO : ','$';DECALARA VARIABLE CON CADENA
;_____________________________________

.CODE           ;COMIENZA EL CODIGO
MAIN PROC FAR   ;PROCESO FAR CON ETIQUETA MAIN
MOV AX, @DATA   ;INICIAMOS EL VALOR CON @DATA
MOV DS, AX      ;PARA SABER LA DIRECCION DE MEMORIA DEL SEG DE DATOS
CALL PANT0      ;DEFINIR LA VENTANA
CALL CURS1      ;DEFINIR EL CURSOR
CALL DESPM1     ;PARA QUE SALGA EL PRIMER MSJ
CALL TECLA1     ;PERMITE LA ENTRADA 1 DE DATOS
CALL CAMPANA1   ;AGREGA A LA CADENA E INGRESA SONIDO Y DELIMITADOR
CALL CURS2      ;DEFINIR EL CURSOR
CALL DESPM2     ;PARA QUE SALGA EL SEGUNDO MSJ
CALL TECLA2     ;PERMITE LA ENTRADA 2 DE DATOS
CALL CAMPANA2   ;AGREGA A LA CADENA E INGRESA SONIDO Y DELIMITADOR
CALL CURS3      ;DEFINIR EL CURSOR
CALL DESPM3     ;PARA QUE SALGA EL TERCER MSJ
CALL TECLA3     ;PERMITE LA ENTRADA 3 DE DATOS
CALL CAMPANA3   ;AGREGA A LA CADENA E INGRESA SONIDO Y DELIMITADOR
CALL CURS11     ;DEFINE EL CURSOR
CALL DESP1      ;PRIMER ENTRADA EN PANTALLA
CALL CURS21     ;DEFINE EL CURSOR
CALL DESP2      ;SEGUNDA ENTRADA EN PANTALLA
CALL CURS31     ;DEFINE EL CURSOR
CALL DESP3      ;TERCERA ENTRADA EN PANTALLA
MOV AX,4C00H    ;SERVICIO PARA FINALIZAR
INT 21H         ;INTERRUPCION 21H
MAIN ENDP       ;FIN MAIN
;_____________________________________

PANT0 PROC NEAR ;FUNCION PARA LA VENTANA 
MOV AH,07H      ;MOVEMOS 06H A AX
MOV BH,47H      ;MOVEMOS 47H A BH
MOV CX,0000H    ;MOVEMOS 0000H EN CX 
MOV DX,184FH    ;MOVEMOS 184FH EN DX
INT 10H         ;INTERRUPCION 10H
RET             ;RETORNAR
PANT0 ENDP      ;FIN FUNC
;_____________________________________

CURS1 PROC NEAR ;FUNC DE CURSOR
MOV AH,02H      ;MOVER 02H A AH
MOV BH,00H      ;MOVER 00H A BH
MOV DX,0404H    ;MOVER 0404H A DX
INT 10H         ;INTERRUPCION 10H
RET             ;RETONAR
CURS1 ENDP      ;FIN FUNC
;_____________________________________

DESPM1 PROC NEAR ;FUNC DEL PRIMER MSJ
MOV AH,09H       ;MOVER 09H A AH
LEA DX,ETIQ1     ;PASAR EL VALOR DE LA ETIQUETA1 EN DX
INT 21H          ;INTERRUPCION 21H
RET              ;RETORNAR
DESPM1 ENDP      ;FIN FUNC
;_____________________________________

TECLA1 PROC NEAR ;FUNCION PARA PERMITIR LA 1ERA ENTRADA DE DATOS
MOV AH,0AH       ;MOVER 0AH A AH
LEA DX, ENTRADA1 ;LO QUE INGRESAMOS EN ENTRADA 1 SE GUARDA EN DX
INT 21H          ;INTERRUPCION 21H
RET              ;RETORNAR
TECLA1 ENDP      ;FIN FUNC
;_____________________________________

CAMPANA1 PROC NEAR   ;FUNC DEL SONIDO 1
MOV BX,00H           ;MOVER 00H A BX
MOV BL, LONREAL1     ;PASAR EL VALOR DE LA LONREAL1 EN BL
MOV INTRO1[BX],07H   ;SONIDO CAMPANA
MOV INTRO1[BX+1],'$' ;DELIMITA LA CADENA
RET                  ;RETORNAR
CAMPANA1 ENDP        ;FUN FUNC
;_____________________________________

CURS2 PROC NEAR   ;FUNCION DE CURSOR DE LA SEGUNDA PALABRA
MOV AH,02H        ;MOVER 02H A AH
MOV BH,00H        ;MOVER 00H A BH
MOV DX,0C04H      ;MOVER 0C04H A DX
INT 10H           ;INTERRUPCION 10H
RET               ;RETORNAR
CURS2 ENDP        ;FIN FUNC
;_____________________________________

DESPM2 PROC NEAR  ;FUNC DEL SEGUNDO MSJ
MOV AH,09H        ;MOVER 09H A AH
LEA DX, ETIQ2     ;LO QUE INGRESAMOS EN ETIQUETA2 SE GUARDA EN DX
INT 21H           ;INTERRUPCION 21H
RET               ;RETORNAA
DESPM2 ENDP       ;FIN FUNC
;_____________________________________

TECLA2 PROC NEAR  ;FUNCION PARA PERMITIR LA 2DA ENTRADA DE DATOS
MOV AH,0AH        ;MOVER 0AH A AH
LEA DX, ENTRADA2  ;LO QUE INGRESAMOS EN ENTRADA2 SE GUARDA EN DX
INT 21H           ;INTERRUPCION 21H
RET               ;RETORNA
TECLA2 ENDP       ;FIN FUNC
;_____________________________________

CAMPANA2 PROC NEAR   ;FUNC DEL SONIDO 2
MOV BX,00H           ;MUEVE 00H A BXX
MOV BL, LONREAL2     ;MUEVE EL VALOR DE LONREAL2 A BL
MOV INTRO2[BX],07H   ;SONIDO CAMPANA
MOV INTRO2[BX+1],'$' ;DELIMITA LA CADENA
RET                  ;RETORNA
CAMPANA2 ENDP        ;FIIN FUNC
;_____________________________________

CURS3 PROC NEAR      ;FUNC DE CURSOR DE LA TERCERA PALABRA 
MOV AH,02H           ;MUEVE 02H A AH
MOV BH,00H           ;MUEVE 00H A BH
MOV DX,1304H         ;MUEVE 1304H A DX
INT 10H              ;INTERRUPCION 10H
RET                  ;RETORNAR
CURS3 ENDP           ;
DESPM3 PROC NEAR     ;
MOV AH,09H           ;
LEA DX, ETIQ3        ;
INT 21H              ;
RET                  ;
DESPM3 ENDP          ;
;_____________________________________

TECLA3 PROC NEAR     ;
MOV AH,0AH           ;
LEA DX, ENTRADA3     ;
INT 21H              ;
RET                  ;
TECLA3 ENDP          ;
;_____________________________________

CAMPANA3 PROC NEAR   ;
MOV BX,00H           ;
MOV BL, LONREAL3     ;
MOV INTRO3[BX],07H   ;
MOV INTRO3[BX+1],'$' ;
RET                  ;
CAMPANA3 ENDP        ;
;_____________________________________

PANT1 PROC NEAR      ;
MOV AH,06H           ;
MOV BH,47H           ;
MOV CX,0000H         ;
MOV DX,184FH         ;
INT 10H              ;
RET                  ;
PANT1 ENDP           ;
;_____________________________________

CURS11 PROC NEAR     ;
MOV AH,02H           ;
MOV BH,00H           ;
MOV DX,0427H         ;
INT 10H              ;
RET                  ;
CURS11 ENDP          ;
;_____________________________________

DESP1 PROC NEAR      ;
MOV AH,09H           ;
LEA DX, INTRO1       ;
INT 21H              ;
RET                  ;
DESP1 ENDP           ;
;_____________________________________

CURS21 PROC NEAR     ;
MOV AH,02H           ;
MOV BH,00H           ;
MOV DX,0C27H         ;
INT 10H              ;
RET                  ;
CURS21 ENDP          ;
;_____________________________________

DESP2 PROC NEAR
MOV AH,09H
LEA DX, INTRO2
INT 21H
RET
DESP2 ENDP
;_____________________________________

CURS31 PROC NEAR
MOV AH,02H
MOV BH,00H
MOV DX,1327H
INT 10H
RET
CURS31 ENDP
;_____________________________________

DESP3 PROC NEAR
MOV AH,09H
LEA DX, INTRO3
INT 21H
RET
DESP3 ENDP
;_____________________________________

END MAIN